// @generated by protoc-gen-es v1.0.0
// @generated from file noted/mailing/v1/mailing.proto (package noted.mailing.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message noted.mailing.v1.Recipient
 */
export declare class Recipient extends Message<Recipient> {
  /**
   * @generated from field: string account_id = 1;
   */
  accountId: string;

  constructor(data?: PartialMessage<Recipient>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "noted.mailing.v1.Recipient";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Recipient;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Recipient;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Recipient;

  static equals(a: Recipient | PlainMessage<Recipient> | undefined, b: Recipient | PlainMessage<Recipient> | undefined): boolean;
}

/**
 * @generated from message noted.mailing.v1.SendEmailRequest
 */
export declare class SendEmailRequest extends Message<SendEmailRequest> {
  /**
   * @generated from field: repeated noted.mailing.v1.Recipient recipients = 1;
   */
  recipients: Recipient[];

  /**
   * @generated from field: string subject = 2;
   */
  subject: string;

  /**
   * @generated from field: string markdown_body = 3;
   */
  markdownBody: string;

  constructor(data?: PartialMessage<SendEmailRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "noted.mailing.v1.SendEmailRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendEmailRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendEmailRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendEmailRequest;

  static equals(a: SendEmailRequest | PlainMessage<SendEmailRequest> | undefined, b: SendEmailRequest | PlainMessage<SendEmailRequest> | undefined): boolean;
}

/**
 * @generated from message noted.mailing.v1.SendEmailResponse
 */
export declare class SendEmailResponse extends Message<SendEmailResponse> {
  constructor(data?: PartialMessage<SendEmailResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "noted.mailing.v1.SendEmailResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SendEmailResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SendEmailResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SendEmailResponse;

  static equals(a: SendEmailResponse | PlainMessage<SendEmailResponse> | undefined, b: SendEmailResponse | PlainMessage<SendEmailResponse> | undefined): boolean;
}

