# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: noted/mailing/v1/mailing.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1enoted/mailing/v1/mailing.proto\x12\x10noted.mailing.v1\"*\n\tRecipient\x12\x1d\n\naccount_id\x18\x01 \x01(\tR\taccountId\"\xa5\x01\n\x11SendEmailsRequest\x12;\n\nrecipients\x18\x01 \x03(\x0b\x32\x1b.noted.mailing.v1.RecipientR\nrecipients\x12\x18\n\x07subject\x18\x02 \x01(\tR\x07subject\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12#\n\rmarkdown_body\x18\x04 \x01(\tR\x0cmarkdownBody\"\x14\n\x12SendEmailsResponse2g\n\nMailingAPI\x12Y\n\nSendEmails\x12#.noted.mailing.v1.SendEmailsRequest\x1a$.noted.mailing.v1.SendEmailsResponse\"\x00\x42\x12Z\x10noted/mailing/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noted.mailing.v1.mailing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020noted/mailing/v1'
  _globals['_RECIPIENT']._serialized_start=52
  _globals['_RECIPIENT']._serialized_end=94
  _globals['_SENDEMAILSREQUEST']._serialized_start=97
  _globals['_SENDEMAILSREQUEST']._serialized_end=262
  _globals['_SENDEMAILSRESPONSE']._serialized_start=264
  _globals['_SENDEMAILSRESPONSE']._serialized_end=284
  _globals['_MAILINGAPI']._serialized_start=286
  _globals['_MAILINGAPI']._serialized_end=389
# @@protoc_insertion_point(module_scope)
