# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protorepo.noted.notes.v1 import notes_pb2 as noted_dot_notes_dot_v1_dot_notes__pb2


class NotesAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNote = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/CreateNote',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteResponse.FromString,
                )
        self.GetNote = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/GetNote',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteResponse.FromString,
                )
        self.UpdateNote = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/UpdateNote',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteResponse.FromString,
                )
        self.DeleteNote = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/DeleteNote',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteResponse.FromString,
                )
        self.ListNotes = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/ListNotes',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesResponse.FromString,
                )
        self.InsertBlock = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/InsertBlock',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockResponse.FromString,
                )
        self.UpdateBlock = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/UpdateBlock',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockResponse.FromString,
                )
        self.UpdateBlockIndex = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/UpdateBlockIndex',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexResponse.FromString,
                )
        self.DeleteBlock = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/DeleteBlock',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockResponse.FromString,
                )
        self.ExportNote = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/ExportNote',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteResponse.FromString,
                )
        self.OnAccountDelete = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/OnAccountDelete',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteResponse.FromString,
                )
        self.ChangeNoteEditPermission = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/ChangeNoteEditPermission',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionResponse.FromString,
                )
        self.GenerateQuiz = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/GenerateQuiz',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizResponse.FromString,
                )
        self.CreateBlockComment = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/CreateBlockComment',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentResponse.FromString,
                )
        self.ListBlockComments = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/ListBlockComments',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsResponse.FromString,
                )
        self.DeleteBlockComment = channel.unary_unary(
                '/noted.notes.v1.NotesAPI/DeleteBlockComment',
                request_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentRequest.SerializeToString,
                response_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentResponse.FromString,
                )


class NotesAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNote(self, request, context):
        """Must be group member, author_account_id defaults to the user making the request. Create a new note in database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNote(self, request, context):
        """Must be group member or author. Return a note from id provided.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNote(self, request, context):
        """Must be author. Can only update `title` or `blocks`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """Must be author. Delete a single note in database. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotes(self, request, context):
        """List notes in a group, authored by a user or both. Must have read access to the notes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertBlock(self, request, context):
        """Must be author. Insert a block of content in a note at a specific index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBlock(self, request, context):
        """Must be author. Update a block content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBlockIndex(self, request, context):
        """Must be author. Update a block index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlock(self, request, context):
        """Must be author. Delete a block in a note and replace the indexes of the others.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportNote(self, request, context):
        """Must be group member. Returns a md or pdf dowloadable file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnAccountDelete(self, request, context):
        """Must be account owner. Delete the account related notes and groups.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeNoteEditPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBlockComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBlockComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlockComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotesAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNote,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteResponse.SerializeToString,
            ),
            'GetNote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNote,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteResponse.SerializeToString,
            ),
            'UpdateNote': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNote,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteResponse.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteResponse.SerializeToString,
            ),
            'ListNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotes,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesResponse.SerializeToString,
            ),
            'InsertBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertBlock,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockResponse.SerializeToString,
            ),
            'UpdateBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBlock,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockResponse.SerializeToString,
            ),
            'UpdateBlockIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBlockIndex,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexResponse.SerializeToString,
            ),
            'DeleteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlock,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockResponse.SerializeToString,
            ),
            'ExportNote': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportNote,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteResponse.SerializeToString,
            ),
            'OnAccountDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.OnAccountDelete,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteResponse.SerializeToString,
            ),
            'ChangeNoteEditPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeNoteEditPermission,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionResponse.SerializeToString,
            ),
            'GenerateQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuiz,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizResponse.SerializeToString,
            ),
            'CreateBlockComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBlockComment,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentResponse.SerializeToString,
            ),
            'ListBlockComments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBlockComments,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsResponse.SerializeToString,
            ),
            'DeleteBlockComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlockComment,
                    request_deserializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentRequest.FromString,
                    response_serializer=noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noted.notes.v1.NotesAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotesAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/CreateNote',
            noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.CreateNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/GetNote',
            noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.GetNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/UpdateNote',
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/DeleteNote',
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/ListNotes',
            noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.ListNotesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/InsertBlock',
            noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.InsertBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/UpdateBlock',
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBlockIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/UpdateBlockIndex',
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.UpdateBlockIndexResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/DeleteBlock',
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExportNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/ExportNote',
            noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.ExportNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OnAccountDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/OnAccountDelete',
            noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.OnAccountDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeNoteEditPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/ChangeNoteEditPermission',
            noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.ChangeNoteEditPermissionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/GenerateQuiz',
            noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.GenerateQuizResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBlockComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/CreateBlockComment',
            noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.CreateBlockCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBlockComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/ListBlockComments',
            noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.ListBlockCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBlockComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/noted.notes.v1.NotesAPI/DeleteBlockComment',
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentRequest.SerializeToString,
            noted_dot_notes_dot_v1_dot_notes__pb2.DeleteBlockCommentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
