name: build-and-lint
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python GRPC Plugin
        run: pip install grpclib protobuf
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.6.0"
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
