name: generate
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: "3.19.4"
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.13.1"
      - name: Generate
        run: |
          find noted -name "*.go" -type f -delete
          find noted -name "*.py" -type f -delete
          buf generate
      - name: Rewrite Python imports
        shell: bash
        run: |
          .github/workflows/scripts/python-sed.sh
      - name: Generate Typescript Axios Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-file: noted.swagger.yaml
          command-args: "-o openapi/typescript-axios"
      - name: Generate Dart Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: dart
          openapi-file: noted.swagger.yaml
          command-args: "-o openapi/dart"
      - name: Generate Dart Dio Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: dart-dio
          openapi-file: noted.swagger.yaml
          command-args: "-o openapi/dart-dio"
      - name: Add generated code
        run: git add -f .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "ci: generate protobuf code"
          commit_user_name: Protobot
          status_options: ""
